#!/bin/bash

set -eE -o pipefail

top=$(pwd)
tmp_patchdir=

function on_exit {
    set +e
    if [[ -n "$tmp_patchdir" && -d "$tmp_patchdir" ]]; then
        rm -rf "$tmp_patchdir"
    fi
    cd "${top}" >/dev/null 2>&1 || true
}

trap 'on_exit' EXIT

if [ "$#" -ne 3 ]; then
    echo "USAGE: $0 repo patchdir ref"
    printf "\t exports patches from 'repo' to 'patchdir' based on 'ref'\n"
    exit 1
fi

# parameters
kernel_submodule=$1
kernel_patchdir=$2
base_ref=$3

cd "${kernel_submodule}"
tmp_patchdir=$(mktemp -d "${top}/.export-patchqueue.XXXXXX")
echo "exporting patchqueue using 'git format-patch [...] ${base_ref}.."
git format-patch \
    --quiet \
    --no-numbered \
    --no-cover-letter \
    --zero-commit \
    --no-signature \
    --diff-algorithm=myers \
    --full-index \
    --output-directory="${tmp_patchdir}" \
    "${base_ref}.."

git checkout "${base_ref}"

cd "${top}"
echo "replacing old exported patchqueue"
rm -f "${kernel_patchdir}"/*.patch
shopt -s nullglob
for patch in "${tmp_patchdir}"/*.patch; do
    mv "$patch" "${kernel_patchdir}/"
done
shopt -u nullglob
